# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ace92fb0d5d3a41652f948f401ff959f3f8a45081c899e460a31ffc998909e99251238f4fd9b472fb31c79a12e8d7262c784726e5c5811550d3b48dd3b38549d

test:
  secret_key_base: 82b4de390bcd1e282c3ec142892cbc661daea4b6ec53984846e290d6b187bd140e3b2a761e2d8c10b3b6c29626d060292b1e40ab963b8d48546f5e0020457080

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
